spring:
  application:
    name: smartlog-backend

  datasource:
    url: jdbc:h2:file:./smartlogdb
    driver-class-name: org.h2.Driver
    username: smartloguser
    password: smartlogpassword
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update